### ISSUE TITLE
Getting a list of webhooks

### ISSUE THREAD

**Issue by jwalton** [mironal/tw-activity#5]
I feel like I'm missing something here, but if I call:

```
    twActivity.getWebhooks(oauth)
    .then(result => console.log(result))
```

I was sort of expecting an array of webhooks.  Instead I get back a Request `response` object.  And digging into the source, it looks like the `body` from Request, which has the information I actually want, gets [thrown away](https://github.com/mironal/tw-activity/blob/8e7210e03cc081d79c2618664009681218e3101a/src/api.ts#L31).

**Comment by mironal** [comment]
Thanks your feedback.

You can use ‘response.body’ for get response body object :smile:

**Comment by jwalton** [comment]
:P

I meant to comment because I figured this out by reading the command line source code, but you beat me to it.  Haha.  But thanks.  :)

**Comment by mironal** [comment]
I will add the more information to README :smile:
